# 📌객체지향의 4대 특성

> 코드의 중복 제거, 유지보수에 용이하게 하는 방법 중 객체지향 프로그래밍의 특성
> 

## 🔎캡슐화와 정보 은닉, 접근 제어자

- 변수와 메서드를 하나도 묶는 패키징 형태

## 🔎상속

- 재사용 + 확장의 개념
- 중복되는 코드는 함수로 분리

## 🔎추상화

- 클래스를 모델링 할 때 필요한 개념
- 구체적인 개개인의 객체를 일반화하는 것

## 🔎다형성

- 다양한 형태를 띌 수 있는 성질
- 참조변수의 타입을 인터페이스 타입으로 사용함으로써 코드의 변경이 줄어들고
- 클래스 간 결합도가 낮아짐

---

# 📌 예외 처리 (Exception handling)

![](https://velog.velcdn.com/images/pdg0526/post/6393c50c-938a-4d6b-beb7-c2ae24ca0670/image.png)


## 🔎오류

> 시스템 레벨에서 발생하고, 사전에 방지하는 것이 목표다.
> 

### 컴파일 오류

- 소스 코드의 컴파일 과정에서 발생하는 오류
- ex) Syntax Error

### 런타임 오류

- 코드가 실행되는 과정에서 발생하는 오류
- 문법은 맞았으나, 실행 과정에서 발생하는 오류
- ex) 경로 오류, nullpointer 오류

### 논리적 오류

- 컴파일, 런타임 오류도 없지만 논리적으로 어긋난 경우
- ex) 나이가 음수인 경우

## 🔎예외

> 사용자의 부주의로 발생하고, 이를 예방, 대처, 처리해야 한다.
> 

- 예외 처리를 함으로써 프로그램의 비정상적인 종료 없이 끝까지 실행할 수 있다.

### ✏예외 처리 코드

```java
try {예외 발생 가능한 명령어}
catch (Exception e) {예외 발생 시 실행할 명령어}
finally {예외 발생 상관없이 실행되는 명령어}
...
```

1. try문 안에서 예외 발생 시
2. new Exception() 인스턴스를 생성하고 e 변수에 초기화
3. 에와 처리 후 finally 실행 

→ 예외가 발생하기 전에는 e 변수는 선언만 되어있지만, 예외가 발생하게 되면 Exception 인스턴스가 생성되어 Exception인스턴스가 초기화된다. 

### ✏예외 처리 과정

1. **예외처리 안할 시**
    
    ```java
    package com;
    
    public class Ex1 {
    
    	public static void main(String[] args) {
    		// TODO Auto-generated method stub
    		
    		int number = 100;
    		
    		for (int i = 0; i < 10; i++) {
    			System.out.println(number / (int)(Math.random()*10));
    		}
    
    	}
    
    }
    ```
    
![](https://velog.velcdn.com/images/pdg0526/post/c9c98500-9aba-46b7-a4a7-d5c68719133b/image.png)

-  반복문이 다 돌기 전에 에러가 발생하면 **실행이 중단됨**
    
2. **예외 처리 시**
    
    ```java
    package com;
    
    public class Ex2 {
    
    	public static void main(String[] args) {
    		// TODO Auto-generated method stub
    		int number = 100;
    		int result = 0;
    		for (int i = 0; i < 10; i++) {
    			
    			try {
    				result = number / (int)(Math.random()*10);
    			} catch (ArithmeticException e) {
    				// TODO: handle exception
    				System.out.println("손님, 0으로 나누시면 안됩니다. ");
    			} // try - catch 끝
    			
    			System.out.println(result);
    		}
    
    	}
    
    }
    ```
    
![](https://velog.velcdn.com/images/pdg0526/post/66a59425-9de7-4bb5-9394-6c722ad02dc1/image.png)
    
- 예외가 발생해도 반복문이 다 **실행된다.**
3. **Exception instance**
    1. exception instance
        
```java
			try {
				result = number / (int)(Math.random()*10);
			} catch (Exception e) {
				// TODO: handle exception
				System.out.println(e);
			} // try - catch 끝
			
			System.out.println(result);
```

  ![](https://velog.velcdn.com/images/pdg0526/post/ede0a094-8c9a-4c2b-9f9a-c845be105136/image.png)

        
- **에러 내용:  에러 원인**
	2. exception.stackTrace()
        
```java
try {
				result = number / (int)(Math.random()*10);
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			} // try - catch 끝
			
			System.out.println(result);
```
![](https://velog.velcdn.com/images/pdg0526/post/aa7501cf-56be-49ed-93e8-978dc8eae3fc/image.png)

- **에러 내용: 에러 원인 at 에러 발생 위치**
   	3. exception.getMessage()
        
```java
try {
				result = number / (int)(Math.random()*10);
			} catch (Exception e) {
				// TODO: handle exception
				System.out.println(e.getMessage());
			} // try - catch 끝
			
			System.out.println(result);
```


![](https://velog.velcdn.com/images/pdg0526/post/8b7b3a05-73a9-4886-9b90-d31b446078f2/image.png)

- 에러 원인
        
        

   4. instance of (downcasting)
        
   ```java
        System.out.println(1);
        System.out.println(2);
        
        try { // 예외 발생 가능
        			System.out.println(3/0);  // 예외 발생! -> 이후  코드는 실행 안됨, 이전은 실행 됨
        			System.out.println(3);	// 바로 catch {}로 이동했기 때문에 해당 코드는 실행되지 않음
        		} catch (Exception e) {
        			// TODO: handle exception
        //			발생한 에러가 ArithmeticException 인지
        			System.out.println(e instanceof ArithmeticException);
        			System.out.println(4);
        
        		} 
        System.out.println(5);
   ```
![](https://velog.velcdn.com/images/pdg0526/post/5544c4ad-18d2-45d1-9efb-a6df05e84f6a/image.png)

- e instanceof ArithmeticException
    - 발생한 에러가 ArithmeticException 인지 아닌지 (return boolean)
- e instanceof NullPointerException
    - 발생한 에러가 NullPointerException 인지 아닌지 (return boolean)

### 🔎예외 만들기

### ✏throw

> 예외 실행하기
> 
- 사용자가 고의로 예외를 실행하는 것

```java
try {
//			예외 인스턴스 생성 (아직 예외가 발생한 건 아님)
			Exception e = new Exception("고의로 발생시킨 예외");
			System.out.println(e);
			
			throw e; // 예외를 던짐(발생시킴)	
//			throw new Exception("고의로 발생시킨 예외2"); // 한줄로 만들기
			
		} catch (Exception e) {
			// TODO: handle exception
			System.out.println("예외 발생");
			System.out.println(e);
		} // end of try-catch
		
		System.out.println("done!");
```

- Exception 예외 이름 = new 예외 클래스

### ✏throws

> 예외가 발생하면, 해당 메서드를 호출한 메서드에게 예외 처리를 위탁하는 기술
> 

```java
package com;

public class MethodEx1 {

	/**
	 * MethodEx1의 멤버 메서드1
	 * method1()의 예외 처리를 짬맞은 메서드
	 * 최상위 객체에게 예외처리 짬때림
	 * @param args
	 * @throws Exception 
	 */
	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub
		method1();
		
	}
	
	/** MethodEx1의 멤버 메서드2
	 * method2()의 예외 처리를 짬맞은 메서드
	 * @throws Exception 
	 */
	static void method1() throws Exception {
		method2();
		System.out.println("method1() 호출");
		
		
	}
	
	/**
	 * MethodEx1의 멤버 메서드3 
	 * 예외를 발생시키는 메서드
	 * 호출부에게 예외처리를 짬때림
	 * 
	 * @throws Exception
	 * 메서드 내부에서 예외가 발생하면
	 * 해당 메서드들 호출한 호출부에서 예외를 처리하도록 책임을 떠넘김
	 */
	static void method2() throws Exception {throw new Exception("예외를 고의로 발생시킴");}

}
```

- main()에서 method1()을 호출하고, method1()에서 method()2를 호출하는 구조이다.
- method2()는 method()1에게 예외처리를 위탁하고 있고, method()1은 main()에게 예외 처리를 위탁하도 있다.
- main()은 최상위 객체에게 예외 처리를 위탁하고 있다.